### ISSUE TITLE
[BUG]Doesn't build on debian sid

### ISSUE THREAD

**Issue by deepthought84** [maxcurzi/tplay#59]
**Describe the bug**
Don't now if an issue is justified, but it doesn't build on debian sid/testing, and I think at least some use it. It also doesn't compile on stable because rust version is too old but this error only occurs on sid/testing

```
Compiling crossbeam-channel v0.5.15
error[E0432]: unresolved import `opencv::core::AlgorithmHint`
 --> /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tplay-0.6.2/src/common/utils.rs:3:14
  |
3 | use opencv::{core::AlgorithmHint, imgproc, prelude::*};
  |              ^^^^^^-------------
  |              |     |
  |              |     help: a similar name exists in the module: `Algorithm`
  |              no `AlgorithmHint` in `opencv::hub::core`

error[E0061]: this function takes 4 arguments but 5 arguments were supplied
    --> /home/stefan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tplay-0.6.2/src/common/utils.rs:66:8
     |
66   |     if imgproc::cvt_color(
     |        ^^^^^^^^^^^^^^^^^^
...
71   |         AlgorithmHint::ALGO_HINT_DEFAULT,
     |         -------------------------------- unexpected argument #5
     |
note: function defined here
    --> /tmp/cargo-installVhgptZ/release/build/opencv-f4d473f14bbacc59/out/opencv/imgproc.rs:6094:9
     |
6094 |     pub fn cvt_color(src: &impl ToInputArray, dst: &mut impl ToOutputArray, code: i32, dst_cn: i32) -> Result<()> {
     |            ^^^^^^^^^
help: remove the extra argument
     |
70   -         0,
71   -         AlgorithmHint::ALGO_HINT_DEFAULT,
70   +         0,
     |

Some errors have detailed explanations: E0061, E0432.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `tplay` (bin "tplay") due to 2 previous errors
error: failed to compile `tplay v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-installVhgptZ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**To Reproduce**
1. run cargo install tplay
2. install dependencies as shown ( libalsa-ocaml-dev libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev libopencv-dev)
3. When all dependency errors are resolved, run again

**Expected behavior**
tplay and it dependencies are built and tplay is installed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian sid , tested also with testing

**Additional context**

**Comment by maxcurzi** [comment]
This has definitely something to do with the OpenCV version installed.
We've seen this before. In my case I had multiple OpenCV versions installed
in different ways (apt, python,  built from source) and only one the built
from source was updated enough to be usable.
That's not to say it's your case, but try to check in how many ways you may
have installed OpenCV and which version is the crate ending up using

**Comment by deepthought84** [comment]
I had it only installed from debian repo, but when I install it from source (doesn't matter if I use latest or latest stable):I still get a linking error:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/usr/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/lib/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" VSLANG="1033" "cc" "-m64" "/tmp/rustcuxFt8u/symbols.o" "<17 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/tmp/cargo-installgpSMNH/release/deps/{libgif_dispose-6c9d9e7fab5f6f8f.rlib,libreqwest-02761aca73911293.rlib,librustls_pki_types-9cfc1667fc6b3c81.rlib,libzeroize-4f9b892d3ce68918.rlib,libhyper_tls-3473daa810056a47.rlib,libtokio_native_tls-75af061bc25f35e5.rlib,libserde_urlencoded-238d4670f20cb45d.rlib,libmime-9bb25d9b8f972aad.rlib,libtower_http-1fe80229b81776fa.rlib,libiri_string-6acbffcfb9b794b9.rlib,libtower-fc2e9802371a5b80.rlib,libsync_wrapper-d8b7ade01429ec9a.rlib,libtower_layer-3a13b6f7e7ee1c14.rlib,libnative_tls-33f1260800f663ef.rlib,libopenssl_probe-bb8f1beb732fa9e7.rlib,libopenssl-ccba8df131382c68.rlib,libforeign_types-991242e964f23837.rlib,libforeign_types_shared-4fd28635032408b3.rlib,libopenssl_sys-8d323bf743b25085.rlib,libhyper_util-fd2856ec2caa3f71.rlib,libbase64-ce06d6eefc70beaf.rlib,libipnet-b1dc61774d12f916.rlib,libtower_service-1c2f202e724dc6df.rlib,libhyper-9d71741c279ecc3b.rlib,libwant-23055941e8aff3e0.rlib,libtry_lock-c36aee5b292014eb.rlib,libhttparse-e6083314a94efc25.rlib,libh2-861dac97f72feabb.rlib,libtracing-3b44697e3c37129e.rlib,libtracing_core-b90ccc77a04d5da0.rlib,libindexmap-b40ef9b8334e6f50.rlib,libequivalent-19c867cc77939acf.rlib,libhashbrown-f93e29d1fb63cd07.rlib,libatomic_waker-5eb372adf39977d3.rlib,libtokio_util-0bcc195090c632fe.rlib,libfutures_channel-3543a67953796d0e.rlib,libtokio-49ddcf30965a5aef.rlib,libsocket2-c682f05a9cfbc623.rlib,libhttp_body_util-da4001f46a2297f4.rlib,libhttp_body-fec1c9334507ba54.rlib,libfutures_util-c552f0771702f46a.rlib,libfutures_io-6ba7290fe337dec6.rlib,libslab-c892f3ad56813553.rlib,libpin_project_lite-2092f9df7b4106e0.rlib,libfutures_sink-80957140d02e2152.rlib,libfutures_task-7bea5e58006cfac2.rlib,libpin_utils-0eae38322dd037d6.rlib,libfutures_core-7420c5cc89d6bc6f.rlib,libhttp-e1241be851a86677.rlib,libbytes-01baf2745608652a.rlib,libfnv-69c00985fcb26f61.rlib,libclap-1884e2c2414680d8.rlib,libclap_builder-9c84ca8df026ff7a.rlib,libstrsim-098d09993af938b8.rlib,libanstream-67311838eed14ac6.rlib,libanstyle_query-799820ecefb21f96.rlib,libis_terminal_polyfill-08aecea0712a0052.rlib,libcolorchoice-462a97d36ff3687b.rlib,libanstyle_parse-caaad6c43b1dd3a8.rlib,libutf8parse-9e72e151286ba4b2.rlib,libclap_lex-529047b3b781ae95.rlib,libanstyle-c1b75675833f4b69.rlib,libcrossterm-db9ea1c23d38a49b.rlib,librustix-89e6ca3fd5a6fa2a.rlib,liblinux_raw_sys-3637875c2e570bf6.rlib,libparking_lot-ff418bb0aaa88d53.rlib,libparking_lot_core-ce2934f57a4266d2.rlib,liblock_api-60a69e59396e8b60.rlib,libscopeguard-bfde4f947c12c8b6.rlib,libsignal_hook_mio-b498ab540459b050.rlib,libsignal_hook-9a421711cfb2c5f2.rlib,libsignal_hook_registry-dae00730dccb46a4.rlib,libmio-5fc94a829890fcfd.rlib,libfast_image_resize-aacd830708853664.rlib,liblibwebp_sys-bd22fc4ecfa4e949.rlib,liburl-0349b6160c3c4be7.rlib,libidna-33151a117eb6ca39.rlib,libutf8_iter-72355edcb3bb8e12.rlib,libidna_adapter-e55fe21ead6b1d05.rlib,libicu_properties-345c07beb106e313.rlib,libicu_properties_data-17e123931e0b7f0d.rlib,libicu_normalizer-119515c735eefae8.rlib,libicu_normalizer_data-c68200005f801ae0.rlib,libicu_collections-49be41e8a7fea4be.rlib,libpotential_utf-64187dc0621ff533.rlib,libicu_provider-440ef06934b07b50.rlib,libicu_locale_core-1ee61ed58e6501cb.rlib,libtinystr-256b70cc6a00a347.rlib,liblitemap-257b3a97dd280d14.rlib,libwriteable-5cf2fc1ebe796efc.rlib,libzerovec-d944dd07c1c31a9c.rlib,libzerotrie-0784cc81c6272d20.rlib,libyoke-4c96737a1f765046.rlib,libstable_deref_trait-feb6a33d6d9e1293.rlib,libzerofrom-8864bf27bac1cf39.rlib,libform_urlencoded-455a5178b4f917f4.rlib,libpercent_encoding-be8acc9a1c7cbf8a.rlib,libopencv-4e38db394213afe1.rlib,libnum-6cbeaa556e5ccb73.rlib,libnum_iter-39948fef2ae029d9.rlib,libnum_complex-c2158f54764a0741.rlib,libimage-d1bb9f6a82b1de93.rlib,libimage_webp-9ed1aaff0a8b2248.rlib,libqoi-2524b90229b2fba9.rlib,libpng-e58e43a183b55c73.rlib,libfdeflate-5787d9bcea157bc2.rlib,libexr-36a49e59052cadaa.rlib,libzune_inflate-e99cde2e5cd1114b.rlib,libbit_field-8102f81560e92fc0.rlib,liblebe-15011c2eeb6d63eb.rlib,libhalf-c41db6f6100f3cad.rlib,libsmallvec-96001fa8f2596d67.rlib,libzune_jpeg-c3b43de5db32287c.rlib,libzune_core-7584b2104cabd3d0.rlib,libgif-29d04744938746df.rlib,libcolor_quant-c21053d75fd75dad.rlib,libbyteorder_lite-390802900401f514.rlib,libravif-0fee319e5b64b49a.rlib,libloop9-9c2173460b3d9b47.rlib,libavif_serialize-19db72694ec3b80b.rlib,libquick_error-439ee332b512f91b.rlib,librgb-1284902c00cbf711.rlib,librav1e-b764b6993ce43e32.rlib,libprofiling-c53dd812c78ee38d.rlib,libav1_grain-9ddc96d2ccf18ca7.rlib,libnom-84bab84836a64e02.rlib,libnum_rational-055d227f83779e00.rlib,libnum_bigint-06f9c22f2c83e96d.rlib,libnum_integer-bc39874e78c140f1.rlib,libanyhow-80d5f567c9dc49af.rlib,libdebug_unreachable-fa5c61646660d3b7.rlib,libmaybe_rayon-ec0239b653536eb1.rlib,librayon-b2e9cbc0f8182b0d.rlib,librayon_core-fda91690fc1c937e.rlib,libcrossbeam_deque-14351de4d4823e63.rlib,libcrossbeam_epoch-f97d0f0e5637e9ae.rlib,libv_frame-6b24bec69e49aeb4.rlib,libaligned_vec-82a6ace1304a6bf2.rlib,libthiserror-a289ba6cd9d9af5b.rlib,libbitstream_io-f2f63d0f2eb49a32.rlib,libitertools-806e886d84b1fb62.rlib,libeither-e534594ddb0dc74f.rlib,libimgref-bb76dd6e86369938.rlib,libnum_traits-1c53b2e1cd71b42b.rlib,libtiff-1573d5e39f1d99d1.rlib,libflate2-6dcf1fb8eb57309d.rlib,libminiz_oxide-90aa286ed2784924.rlib,libsimd_adler32-b7c45189933ade17.rlib,libcrc32fast-a601c567d0897eed.rlib,libweezl-930c5ca84bcd25a3.rlib,libjpeg_decoder-9ec84659e055582a.rlib,libthiserror-1e83f8079466b1ad.rlib,libtempfile-6a7499d6b9c4ebeb.rlib,libgetrandom-40d00849ad6ea050.rlib,libfastrand-0e9dc3387774ec4c.rlib,libonce_cell-3ab8704a78ce150e.rlib,librustix-0dccadc332afbe53.rlib,liblinux_raw_sys-d6b43801852f10b5.rlib,libserde_json-b4a81f309b81d4ab.rlib,libmemchr-aa39b558eaa9deb4.rlib,libitoa-6add5f87b25323a8.rlib,libryu-79fd6bb0c3a783a5.rlib,libserde-73dcfdcdb5c8afaa.rlib,libcrossbeam_channel-0c9550d49c7d6162.rlib,libcrossbeam_utils-f57b084d78b2bc3d.rlib,librodio-ea96f697fa07a0ba.rlib,libhound-239343fed7bf2a83.rlib,liblewton-7c6406099214c110.rlib,libogg-7bdda1502ef1def6.rlib,libtinyvec-c34888dc4b88bc56.rlib,libtinyvec_macros-a13c9307a9093246.rlib,libbyteorder-924ec120560be4df.rlib,libclaxon-4b03f86ea4a04db0.rlib,libsymphonia-4118151038b8d5bd.rlib,libsymphonia_metadata-e8e4138c96d7458d.rlib,libencoding_rs-9e38056643f629ac.rlib,libsymphonia_bundle_mp3-6e0e19fea90dfe19.rlib,libsymphonia_core-13bba4b6846c42e9.rlib,libbytemuck-573c48f8165df9ee.rlib,liblog-bff9bc24cced46f9.rlib,liblazy_static-ebeb2c2e6f203807.rlib,libbitflags-f516cbc37c537b89.rlib,libarrayvec-1341ab7663e7ddcc.rlib,libcpal-29b447458a9f043e.rlib,libdasp_sample-f103fb9315e5b850.rlib,libalsa-5d93651135d591ea.rlib,libcfg_if-4f70ac39b404d89c.rlib,libbitflags-96f2de4b85899444.rlib,libalsa_sys-bee75c6ba3b871b1.rlib,liblibc-1e6d5b8712786771.rlib}" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libstd-735cce14533b4b14.rlib,libpanic_unwind-b6737e136067c5af.rlib,libobject-1303c4fadc744db1.rlib,libmemchr-4307c8d3168c78e3.rlib,libaddr2line-78c32e4a87333dbd.rlib,libgimli-0fc0e49acceead35.rlib,librustc_demangle-a0b9c22792c85e39.rlib,libstd_detect-83f7e4a793b39811.rlib,libhashbrown-0d7f81c4b968ca96.rlib,librustc_std_workspace_alloc-6a65191895fd580e.rlib,libminiz_oxide-357876da66360401.rlib,libadler-0c1d85aa00dff5fa.rlib,libunwind-d8e6262062f0cd85.rlib,libcfg_if-2424c0e00d5dc157.rlib,liblibc-d9b6e8d963ea0be1.rlib,liballoc-ecc6700de60a5b56.rlib,librustc_std_workspace_core-6129c8f9aed81c8b.rlib,libcore-2d4b9a0883bc3ecf.rlib,libcompiler_builtins-bdfb7378ad19badb.rlib}" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lstdc++" "-lopencv_gapi" "-lopencv_highgui" "-lopencv_ml" "-lopencv_objdetect" "-lopencv_photo" "-lopencv_stitching" "-lopencv_video" "-lopencv_videoio" "-lopencv_imgcodecs" "-lopencv_dnn" "-lopencv_calib3d" "-lopencv_features2d" "-lopencv_flann" "-lopencv_imgproc" "-lopencv_core" "-lasound" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/tmp/cargo-installgpSMNH/release/build/libwebp-sys-4dda503b2968a710/out" "-L" "/tmp/cargo-installgpSMNH/release/build/opencv-f4d473f14bbacc59/out" "-L" "/usr/local/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installgpSMNH/release/deps/tplay-83a15da136594e2b" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: /usr/bin/ld: /tmp/cargo-installgpSMNH/release/deps/libopencv-4e38db394213afe1.rlib(e9c67c5f1470be46-imgproc.o): in function `cv_cvtColor_const__InputArrayR_const__OutputArrayR_int_int_AlgorithmHint':
          imgproc.cpp:(.text.cv_cvtColor_const__InputArrayR_const__OutputArrayR_int_int_AlgorithmHint+0xa): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int, cv::AlgorithmHint)'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `tplay` (bin "tplay") due to 1 previous error
error: failed to compile `tplay v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-installgpSMNH`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
``

**Comment by deepthought84** [comment]
Ah good to know I just installed tplay from AUR inside distrobox, which also works

**Comment by maxcurzi** [comment]
this should work on 0.6.3 by following the installation guide in the readme. Just tested on latest Debian release in virtualbox.
